insert into Addrese (PostalCode, Addrese) values ('3720', '309 Mariners Cove Court');
insert into Addrese (PostalCode, Addrese) values ('4250', '39 Mayfield Point');
insert into Addrese (PostalCode, Addrese) values ('4450', '77506 Dovetail Circle');
insert into Addrese (PostalCode, Addrese) values ('4771', '3 Main Place');
insert into Addrese (PostalCode, Addrese) values ('4621', '19 Toban Court');
insert into Addrese (PostalCode, Addrese) values ('4880', '1469 Corry Street');
insert into Addrese (PostalCode, Addrese) values ('5960', '49424 Prairie Rose Lane');
insert into Addrese (PostalCode, Addrese) values ('6840', '141 West Junction');
insert into Addrese (PostalCode, Addrese) values ('5464', '695 Colorado Point');
insert into Addrese (PostalCode, Addrese) values ('7250', '33693 Coolidge Plaza');
insert into Addrese (PostalCode, Addrese) values ('8300', '61932 Hermina Hill');
insert into Addrese (PostalCode, Addrese) values ('6683', '666 Bay Drive');
insert into Addrese (PostalCode, Addrese) values ('8520', '593 Veith Park');
insert into Addrese (PostalCode, Addrese) values ('5220', '4 Aberg Place');
insert into Addrese (PostalCode, Addrese) values ('5220', '3 Blackbird Avenue');
insert into Addrese (PostalCode, Addrese) values ('5960', '17824 Mayer Point');
insert into Addrese (PostalCode, Addrese) values ('7250', '6044 Anhalt Court');
insert into Addrese (PostalCode, Addrese) values ('5464', '10 Forest Lane');
insert into Addrese (PostalCode, Addrese) values ('5210', '83 Ohio Lane');